steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-01-6b0f85393c04/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s

options:
  pool:
    name: 'projects/qwiklabs-gcp-01-6b0f85393c04/locations/us-west1/workerPools/ASD'



  
 
    


